sudo: required
language: node
services: docker

install:
  - echo "install nothing!"

script:
  - echo "no tests!"

after_success:
  - |
    if [[ "$TRAVIS_BRANCH" == "master" ]]; then
      docker version
      docker login -e="$DOCKER_EMAIL" -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
      docker build -t jackytck/rabbit-node-oss-s3-docker:v0.0.2 .
      docker push jackytck/rabbit-node-oss-s3-docker:v0.0.2
    fi
