sudo: required
language: node
services: docker

install:
  - echo "install nothing!"

script:
  - echo "no tests!"

after_success:
  - |
    if [[ "$TRAVIS_BRANCH" == "master" ]]; then
      docker build -t jackytck/rabbit-node-oss-s3-docker:v0.0.2 .
      echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
      docker push jackytck/rabbit-node-oss-s3-docker:v0.0.2
    fi
