sudo: required

language: node

services:
  - docker

install:
  - echo "install nothing!"

script:
  - echo "no tests!"

deploy:
  provider: script
  script: bash docker_push
  on:
    branch: master
